#pragma once

//#define USE_LOGGER 1
#define SKIP_GL_CHECKS 1

#define INITIAL_LIVES_VALUE 9
#define DEFAULT_DELTATIME 16

#define BEGIN_BALL_VELOCITY 3.f
#define BEGIN_BOARD_VELOCITY 0.48f

// Range of angles
#define BEGIN_ANGLE 30.0
#define END_RIGHT_ANGLE 70.0
#define BEGIN_LEFT_ANGLE 110.0
#define END_ANGLE 150.0

#define NUM_OF_CALCULATED_POINTS 5
#define INCREASE_VELOCITY_STEP .01f
#define INCREASE_DEFAULT_STEP 1.f


// Video control dimensions
#define PLAYER_CONTROLS_PANEL_HEIGHT 20
